spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: dev

comment.avatar: /images/avatar.jpeg
server:
  port: 8116
#阿里云信息配置，阿里云的对象存储
aliyun:
  oss:
    file:
      endpoint:
      keyid:
      keysecret:
      bucketname:


